version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.10.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm build 
      - persist_to_workspace:
          root: .
          paths:
            - build/
  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run: aws s3 sync /workspace/build s3://my-artifacts-bucket-v1 --delete

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

