version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.10.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      # - run: npm run build 
      - persist_to_workspace:
          root: .
          paths:
            - index.js
            - package.json
            - node_modules/
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Add SSH Key
          command: |
            echo "$AWS_PRIVATE_KEY" > private_key.pem
            chmod 600 private_key.pem
      - run:
          name: Deploy to EC2
          command: |
            scp -i private_key.pem -r /workspace/* $AWS_EC2_USER@$AWS_EC2_HOST:/home/$AWS_EC2_USER/app
            ssh -i private_key.pem $AWS_EC2_USER@$AWS_EC2_HOST << 'EOF'
              cd /home/$AWS_EC2_USER/app
              npm install
              pm2 restart all || pm2 start npm --name "node-app" -- start
            EOF
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

